name: GitHub Actions

on:
  push:
    tags:
      [ 'v**' ]
        
jobs:
  Image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker build -t ${{ secrets.DOCKERHUB_REPOSITORY_NAME }}/backup-buddy:${{ github.ref_name }} -f ./Dockerfile .
          docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_PASSWORD_TOKEN }}
          docker push ${{ secrets.DOCKERHUB_REPOSITORY_NAME }}/backup-buddy:${{ github.ref_name }}